clone_depth: 1
pull_requests:
  do_not_increment_build_number: true

version: '{branch} build {build}'
image: Visual Studio 2017

environment:
  BOOST_ROOT: C:\Libraries\boost_1_69_0
  CMAKE_GENERATOR: Visual Studio 15 2017
  PLATFORM_TOOLSET: v141_xp

cache:
  - boost.cached -> appveyor_build_boost.bat
  - C:\Libraries\boost_1_69_0\stage -> appveyor_build_boost.bat
  - C:\Libraries\boost_1_69_0\stage_x64 -> appveyor_build_boost.bat

init:
  - dir C:\Libraries
  - git --version
  - git config --global core.autocrlf true

install:
  - .\appveyor.install.bat

build_script:
  - if "%APPVEYOR_REPO_TAG%" == "false" set WEASEL_BUILD=%APPVEYOR_BUILD_NUMBER%
  - .\build.bat data hant weasel installer

artifacts:
  - path: output\archives\weasel-0.14.3.*-installer.exe
    name: Weasel

deploy:
  - provider: BinTray
    username: yuankk
    api_key: &bintray_api_key
      secure: 7x1Gu8m7EqEwdJDaYy7mX3qHcF4cCJx2JHfuWMg+QmmDMgRfegHc0TTEAKNaniZQ
    subject: naihe
    repo: weasel
    package: release
    version: 0.14.3
    publish: false
    override: false
    explode: false
    on:
      APPVEYOR_REPO_TAG: true
  - provider: BinTray
    username: yuankk
    api_key: *bintray_api_key
    subject: naihe
    repo: weasel
    package: testing
    version: 0.14.3.$(APPVEYOR_BUILD_NUMBER)
    publish: true
    override: false
    explode: false
    on:
      branch: master
